# generated by datamodel-codegen:
#   filename:  https://api.iri.nersc.gov/api/v2/openapi.json
#   timestamp: 2026-06-25T09:46:17+00:00

from __future__ import annotations
from enum import StrEnum
from typing import Annotated
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AllocationUnit(StrEnum):
    """Units for allocation"""

    node_hours = "node_hours"
    bytes = "bytes"
    inodes = "inodes"


class BodyUpload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    file: Annotated[bytes, Field(title="File")]
    """File to be uploaded as `multipart/form-data`"""


class Capability(BaseModel):
    """
    An aspect of a resource that can have an allocation.
    For example, Perlmutter nodes with GPUs
    For some resources at a facility, this will be 1 to 1 with the resource.
    It is a way to further subdivide a resource into allocatable sub-resources.
    The word "capability" is also known to users as something they need for a job to run. (eg. gpu)
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["urn:iri:object:1234"], title="Id")]
    """
    The unique identifier for the object. Typically a UUID or URN.

    Example: 'urn:iri:object:1234'
    """
    name: Annotated[str | None, Field(examples=["Perlmutter GPU"], title="Name")] = None
    """
    The long name of the object.

    Example: 'Perlmutter GPU'
    """
    description: Annotated[
        str | None,
        Field(examples=["High-performance GPU compute resource"], title="Description"),
    ] = None
    """
    Human-readable description of the object.

    Example: 'High-performance GPU compute resource'
    """
    last_modified: Annotated[
        AwareDatetime | None,
        Field(examples=["2026-02-21T12:00:00Z"], title="Last Modified"),
    ] = None
    """
    ISO 8601 timestamp when this object was last modified.

    Example: '2026-02-21T12:00:00Z'
    """
    units: Annotated[
        list[AllocationUnit], Field(examples=[["node_hours"]], title="Units")
    ]
    """
    Allocation units supported by this capability

    Example: ['node_hours']
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """The canonical URL of this object"""


class CompressionType(StrEnum):
    """Defines the type of compression to be used for compressing or extracting files."""

    none = "none"
    bzip2 = "bzip2"
    gzip = "gzip"
    xz = "xz"


class SupportUri(RootModel[AnyUrl]):
    root: Annotated[
        AnyUrl, Field(examples=["https://support.es.net"], title="Support Uri")
    ]
    """
    Link to facility support portal.

    Example: 'https://support.es.net'
    """


class Facility(BaseModel):
    """Facility representation, including associated Sites."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["urn:iri:object:1234"], title="Id")]
    """
    The unique identifier for the object. Typically a UUID or URN.

    Example: 'urn:iri:object:1234'
    """
    name: Annotated[str | None, Field(examples=["Perlmutter GPU"], title="Name")] = None
    """
    The long name of the object.

    Example: 'Perlmutter GPU'
    """
    description: Annotated[
        str | None,
        Field(examples=["High-performance GPU compute resource"], title="Description"),
    ] = None
    """
    Human-readable description of the object.

    Example: 'High-performance GPU compute resource'
    """
    last_modified: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Last Modified")
    ]
    """
    ISO 8601 timestamp when this object was last modified.

    Example: '2026-02-21T12:00:00Z'
    """
    short_name: Annotated[str | None, Field(examples=["ESnet"], title="Short Name")] = (
        None
    )
    """
    Common or short name of the Facility.

    Example: 'ESnet'
    """
    organization_name: Annotated[
        str | None,
        Field(examples=["Energy Sciences Network"], title="Organization Name"),
    ] = None
    """
    Operating organization's name.

    Example: 'Energy Sciences Network'
    """
    support_uri: Annotated[
        SupportUri | None,
        Field(examples=["https://support.es.net"], title="Support Uri"),
    ] = None
    """
    Link to facility support portal.

    Example: 'https://support.es.net'
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """The canonical URL of this object"""
    site_uris: Annotated[list[str], Field(frozen=True, title="Site Uris")]
    """URIs of associated Sites."""


class IncidentType(StrEnum):
    """Represents the type of an incident."""

    planned = "planned"
    unplanned = "unplanned"
    reservation = "reservation"


class Duration(RootModel[int]):
    root: Annotated[int, Field(examples=[30, 60, 120], ge=1, title="Duration")]
    """
    Duration in seconds

    Examples:
    - 30
    - 60
    - 120
    """


class QueueName(RootModel[str]):
    root: Annotated[str, Field(examples=["debug"], min_length=1, title="Queue Name")]
    """
    Name of the queue or partition to submit the job to

    Example: 'debug'
    """


class Account(RootModel[str]):
    root: Annotated[str, Field(examples=["proj123"], min_length=1, title="Account")]
    """
    Account or project to charge for resource usage

    Example: 'proj123'
    """


class ReservationId(RootModel[str]):
    root: Annotated[
        str, Field(examples=["resv-42"], min_length=1, title="Reservation Id")
    ]
    """
    ID of a reservation to use for the job

    Example: 'resv-42'
    """


class JobAttributes(BaseModel):
    """Additional attributes and scheduling parameters for a job."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    duration: Annotated[
        Duration | None, Field(examples=[30, 60, 120], title="Duration")
    ] = None
    """
    Duration in seconds

    Examples:
    - 30
    - 60
    - 120
    """
    queue_name: Annotated[
        QueueName | None, Field(examples=["debug"], title="Queue Name")
    ] = None
    """
    Name of the queue or partition to submit the job to

    Example: 'debug'
    """
    account: Annotated[Account | None, Field(examples=["proj123"], title="Account")] = (
        None
    )
    """
    Account or project to charge for resource usage

    Example: 'proj123'
    """
    reservation_id: Annotated[
        ReservationId | None, Field(examples=["resv-42"], title="Reservation Id")
    ] = None
    """
    ID of a reservation to use for the job

    Example: 'resv-42'
    """
    custom_attributes: Annotated[
        dict[str, str] | None,
        Field(examples=[{"constraint": "gpu"}], title="Custom Attributes"),
    ] = None
    """
    Custom scheduler-specific attributes as key-value pairs

    Example: {'constraint': 'gpu'}
    """


class Executable(RootModel[str]):
    root: Annotated[
        str, Field(examples=["/usr/bin/python"], min_length=1, title="Executable")
    ]
    """
    Path to the executable to run. If container is specified, this will be used as the entrypoint to the container.

    Example: '/usr/bin/python'
    """


class Directory(RootModel[str]):
    root: Annotated[
        str, Field(examples=["/home/user/work"], min_length=1, title="Directory")
    ]
    """
    Working directory for the job

    Example: '/home/user/work'
    """


class Name(RootModel[str]):
    root: Annotated[str, Field(examples=["my-job"], min_length=1, title="Name")]
    """
    Name of the job

    Example: 'my-job'
    """


class StdinPath(RootModel[str]):
    root: Annotated[
        str, Field(examples=["/home/user/input.txt"], min_length=1, title="Stdin Path")
    ]
    """
    Path to file to use as standard input

    Example: '/home/user/input.txt'
    """


class StdoutPath(RootModel[str]):
    root: Annotated[
        str,
        Field(examples=["/home/user/output.txt"], min_length=1, title="Stdout Path"),
    ]
    """
    Path to file to write standard output

    Example: '/home/user/output.txt'
    """


class StderrPath(RootModel[str]):
    root: Annotated[
        str, Field(examples=["/home/user/error.txt"], min_length=1, title="Stderr Path")
    ]
    """
    Path to file to write standard error

    Example: '/home/user/error.txt'
    """


class PreLaunch(RootModel[str]):
    root: Annotated[
        str, Field(examples=["module load cuda"], min_length=1, title="Pre Launch")
    ]
    """
    Script or commands to run before launching the job

    Example: 'module load cuda'
    """


class PostLaunch(RootModel[str]):
    root: Annotated[
        str, Field(examples=["echo done"], min_length=1, title="Post Launch")
    ]
    """
    Script or commands to run after the job completes

    Example: 'echo done'
    """


class Launcher(RootModel[str]):
    root: Annotated[str, Field(examples=["srun"], min_length=1, title="Launcher")]
    """
    Job launcher to use (e.g., 'mpirun', 'srun')

    Example: 'srun'
    """


class JobState(StrEnum):
    """
    from: https://exaworks.org/psij-python/docs/v/0.9.11/_modules/psij/job_state.html#JobState

    An enumeration holding the possible job states.

    The possible states are: `NEW`, `QUEUED`, `ACTIVE`, `COMPLETED`, `FAILED`, and `CANCELED`.
    """

    new = "new"
    queued = "queued"
    held = "held"
    active = "active"
    completed = "completed"
    failed = "failed"
    canceled = "canceled"


class JobStatus(BaseModel):
    """Represents the status of a job."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    state: Annotated[JobState, Field(examples=["queued"])]
    """
    Current state of the job

    Example: 'queued'
    """
    time: Annotated[float | None, Field(examples=[1708531200.0], title="Time")] = None
    """
    Timestamp associated with the status (seconds since epoch)

    Example: 1708531200.0
    """
    message: Annotated[
        str | None, Field(examples=["Job is waiting in queue"], title="Message")
    ] = None
    """
    Human-readable status message

    Example: 'Job is waiting in queue'
    """
    exit_code: Annotated[int | None, Field(examples=[0], title="Exit Code")] = None
    """
    Process exit code if the job has finished

    Example: 0
    """
    meta_data: Annotated[dict[str, object] | None, Field(title="Meta Data")] = None
    """Backend-specific metadata associated with the job status"""


class PostCompressRequest(BaseModel):
    """Represents a request to compress a file."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    target_path: Annotated[
        str, Field(examples=["/home/user/file.tar.gz"], title="Target Path")
    ]
    """
    Path to the compressed file

    Example: '/home/user/file.tar.gz'
    """
    match_pattern: Annotated[
        str | None, Field(examples=[".*\\.txt$"], title="Match Pattern")
    ] = None
    """
    Regex pattern to filter files to compress

    Example: '.*\\\\.txt$'
    """
    dereference: Annotated[bool, Field(examples=[True], title="Dereference")] = False
    """
    If set to `true`, it follows symbolic links and archive the files they point to instead of the links themselves.

    Example: True
    """
    compression: Annotated[CompressionType, Field(examples=["gzip"])] = (
        CompressionType.gzip
    )
    """
    Defines the type of compression to be used. By default gzip is used.

    Example: 'gzip'
    """


class PostCopyRequest(BaseModel):
    """Represents a request to copy a file."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    target_path: Annotated[
        str, Field(examples=["/home/user/dir/file.new"], title="Target Path")
    ]
    """
    Target path of the copy operation

    Example: '/home/user/dir/file.new'
    """
    dereference: Annotated[bool, Field(examples=[True], title="Dereference")] = False
    """
    If set to `true`, it follows symbolic links and copies the files they point to instead of the links themselves.

    Example: True
    """


class PostExtractRequest(BaseModel):
    """Represents a request to extract a compressed file."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    target_path: Annotated[str, Field(examples=["/home/user/dir"], title="Target Path")]
    """
    Path to the directory where to extract the compressed file

    Example: '/home/user/dir'
    """
    compression: Annotated[CompressionType, Field(examples=["gzip"])] = (
        CompressionType.gzip
    )
    """
    Defines the type of compression to be used. By default gzip is used.

    Example: 'gzip'
    """


class PostFileSymlinkRequest(BaseModel):
    """Represents a request to create a symbolic link."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    link_path: Annotated[str, Field(examples=["/home/user/newlink"], title="Link Path")]
    """
    Path to the new symlink

    Example: '/home/user/newlink'
    """


class PostMakeDirRequest(BaseModel):
    """Represents a request to create a directory."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    parent: Annotated[bool, Field(examples=[True], title="Parent")] = False
    """
    If set to `true` creates all its parent directories if they do not already exist

    Example: True
    """


class PostMoveRequest(BaseModel):
    """Represents a request to move a file."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    target_path: Annotated[
        str, Field(examples=["/home/user/dir/file.new"], title="Target Path")
    ]
    """
    Target path of the move operation

    Example: '/home/user/dir/file.new'
    """


class Problem(BaseModel):
    """Error structure for REST interface based on RFC 9457, "Problem Details for HTTP APIs.\""""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Annotated[AnyUrl, Field(title="Type")]
    """A URI reference that identifies the problem type."""
    status: Annotated[int, Field(examples=[404], ge=100, le=599, title="Status")]
    """
    The HTTP status code for this occurrence.

    Example: 404
    """
    title: Annotated[str | None, Field(examples=["Not Found"], title="Title")] = None
    """
    Short human-readable summary.

    Example: 'Not Found'
    """
    detail: Annotated[
        str | None, Field(examples=["Descriptive text."], title="Detail")
    ] = None
    """
    Human-readable explanation.

    Example: 'Descriptive text.'
    """
    instance: Annotated[
        str, Field(examples=["http://localhost/api/v2/resource/123"], title="Instance")
    ]
    """
    A URI reference identifying this occurrence.

    Example: 'http://localhost/api/v2/resource/123'
    """


class Project(BaseModel):
    """A project and its users at a facility"""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["proj-abc123"], title="Id")]
    """
    Unique identifier of the project.

    Example: 'proj-abc123'
    """
    name: Annotated[str, Field(examples=["Climate Simulation"], title="Name")]
    """
    Human-readable name of the project.

    Example: 'Climate Simulation'
    """
    description: Annotated[
        str,
        Field(
            examples=["Research project studying atmospheric dynamics."],
            title="Description",
        ),
    ]
    """
    Detailed description of the project.

    Example: 'Research project studying atmospheric dynamics.'
    """
    user_ids: Annotated[
        list[str], Field(examples=[["user-123", "user-456"]], title="User Ids")
    ]
    """
    List of user identifiers participating in the project.

    Example: ['user-123', 'user-456']
    """
    last_modified: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T14:30:00Z"], title="Last Modified")
    ]
    """
    Timestamp of the last modification of the project.

    Example: '2026-02-21T14:30:00Z'
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """URI to this project resource"""


class PutFileChmodRequest(BaseModel):
    """Represents a request to change file permissions."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    mode: Annotated[str, Field(examples=["777"], title="Mode")]
    """
    Mode in octal permission format

    Example: '777'
    """


class PutFileChownRequest(BaseModel):
    """Represents a request to change file ownership."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Annotated[str | None, Field(examples=["/home/user/dir"], title="Path")] = None
    """
    Source file or directory path

    Example: '/home/user/dir'
    """
    owner: Annotated[str, Field(examples=["user"], title="Owner")] = ""
    """
    User name of the new user owner of the file

    Example: 'user'
    """
    group: Annotated[str, Field(examples=["my-group"], title="Group")] = ""
    """
    Group name of the new group owner of the file

    Example: 'my-group'
    """


class Resolution(StrEnum):
    """Represents the resolution status of an incident."""

    unresolved = "unresolved"
    cancelled = "cancelled"
    completed = "completed"
    extended = "extended"
    pending = "pending"


class NodeCount(RootModel[int]):
    root: Annotated[int, Field(examples=[2], ge=1, title="Node Count")]
    """
    Number of compute nodes to allocate

    Example: 2
    """


class ProcessCount(RootModel[int]):
    root: Annotated[int, Field(examples=[64], ge=1, title="Process Count")]
    """
    Total number of processes to launch

    Example: 64
    """


class ProcessesPerNode(RootModel[int]):
    root: Annotated[int, Field(examples=[32], ge=1, title="Processes Per Node")]
    """
    Number of processes to launch per node

    Example: 32
    """


class CpuCoresPerProcess(RootModel[int]):
    root: Annotated[int, Field(examples=[2], ge=1, title="Cpu Cores Per Process")]
    """
    Number of CPU cores to allocate per process

    Example: 2
    """


class GpuCoresPerProcess(RootModel[int]):
    root: Annotated[int, Field(examples=[1], ge=1, title="Gpu Cores Per Process")]
    """
    Number of GPU cores to allocate per process

    Example: 1
    """


class Memory(RootModel[int]):
    root: Annotated[int, Field(examples=[17179869184], ge=1, title="Memory")]
    """
    Amount of memory to allocate in bytes

    Example: 17179869184
    """


class ResourceSpec(BaseModel):
    """Specification of computational resources required for a job."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    node_count: Annotated[NodeCount | None, Field(examples=[2], title="Node Count")] = (
        None
    )
    """
    Number of compute nodes to allocate

    Example: 2
    """
    process_count: Annotated[
        ProcessCount | None, Field(examples=[64], title="Process Count")
    ] = None
    """
    Total number of processes to launch

    Example: 64
    """
    processes_per_node: Annotated[
        ProcessesPerNode | None, Field(examples=[32], title="Processes Per Node")
    ] = None
    """
    Number of processes to launch per node

    Example: 32
    """
    cpu_cores_per_process: Annotated[
        CpuCoresPerProcess | None, Field(examples=[2], title="Cpu Cores Per Process")
    ] = None
    """
    Number of CPU cores to allocate per process

    Example: 2
    """
    gpu_cores_per_process: Annotated[
        GpuCoresPerProcess | None, Field(examples=[1], title="Gpu Cores Per Process")
    ] = None
    """
    Number of GPU cores to allocate per process

    Example: 1
    """
    exclusive_node_use: Annotated[
        bool, Field(examples=[True], title="Exclusive Node Use")
    ] = True
    """
    Whether to request exclusive use of allocated nodes

    Example: True
    """
    memory: Annotated[Memory | None, Field(examples=[17179869184], title="Memory")] = (
        None
    )
    """
    Amount of memory to allocate in bytes

    Example: 17179869184
    """


class ResourceType(StrEnum):
    """Represents the type of a resource."""

    website = "website"
    service = "service"
    compute = "compute"
    system = "system"
    storage = "storage"
    network = "network"
    unknown = "unknown"


class Site(BaseModel):
    """A physical site that hosts resources and is part of a facility."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["urn:iri:object:1234"], title="Id")]
    """
    The unique identifier for the object. Typically a UUID or URN.

    Example: 'urn:iri:object:1234'
    """
    name: Annotated[str | None, Field(examples=["Perlmutter GPU"], title="Name")] = None
    """
    The long name of the object.

    Example: 'Perlmutter GPU'
    """
    description: Annotated[
        str | None,
        Field(examples=["High-performance GPU compute resource"], title="Description"),
    ] = None
    """
    Human-readable description of the object.

    Example: 'High-performance GPU compute resource'
    """
    last_modified: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Last Modified")
    ]
    """
    ISO 8601 timestamp when this object was last modified.

    Example: '2026-02-21T12:00:00Z'
    """
    short_name: Annotated[str | None, Field(examples=["NERSC"], title="Short Name")] = (
        None
    )
    """
    Common or short name of the Site.

    Example: 'NERSC'
    """
    operating_organization: Annotated[
        str | None,
        Field(
            examples=["Lawrence Berkeley National Laboratory"],
            title="Operating Organization",
        ),
    ]
    """
    Organization operating the Site.

    Example: 'Lawrence Berkeley National Laboratory'
    """
    country_name: Annotated[
        str | None, Field(examples=["United States"], title="Country Name")
    ] = None
    """
    Country name of the Location.

    Example: 'United States'
    """
    locality_name: Annotated[
        str | None, Field(examples=["Berkeley"], title="Locality Name")
    ] = None
    """
    City or locality name of the Location.

    Example: 'Berkeley'
    """
    state_or_province_name: Annotated[
        str | None, Field(examples=["California"], title="State Or Province Name")
    ] = None
    """
    State or province name of the Location.

    Example: 'California'
    """
    street_address: Annotated[
        str | None, Field(examples=["1 Cyclotron Rd"], title="Street Address")
    ] = None
    """
    Street address of the Location.

    Example: '1 Cyclotron Rd'
    """
    unlocode: Annotated[str | None, Field(examples=["USOAK"], title="Unlocode")] = None
    """
    United Nations trade and transport location code.

    Example: 'USOAK'
    """
    altitude: Annotated[float | None, Field(examples=[52.0], title="Altitude")] = None
    """
    Altitude of the Location.

    Example: 52.0
    """
    latitude: Annotated[float | None, Field(examples=[37.8762], title="Latitude")] = (
        None
    )
    """
    Latitude of the Location.

    Example: 37.8762
    """
    longitude: Annotated[
        float | None, Field(examples=[-122.2506], title="Longitude")
    ] = None
    """
    Longitude of the Location.

    Example: -122.2506
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """The canonical URL of this object"""
    resource_uris: Annotated[list[str], Field(frozen=True, title="Resource Uris")]
    """URIs of Resources hosted at this Site."""


class Status(StrEnum):
    """Represents the status of a resource."""

    up = "up"
    down = "down"
    degraded = "degraded"
    unknown = "unknown"


class TaskCommand(BaseModel):
    """Represents a command to be executed as part of a task."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    router: Annotated[str, Field(examples=["filesystem"], title="Router")]
    """
    Router name the task comes from

    Example: 'filesystem'
    """
    command: Annotated[str, Field(examples=["chmod"], title="Command")]
    """
    Command to execute

    Example: 'chmod'
    """
    args: Annotated[
        dict[str, object],
        Field(examples=[{"mode": "755", "path": "/home/user/file"}], title="Args"),
    ]
    """
    Command arguments as key-value pairs

    Example: {'mode': '755', 'path': '/home/user/file'}
    """


class TaskStatus(StrEnum):
    """Represents the status of a task."""

    pending = "pending"
    active = "active"
    completed = "completed"
    failed = "failed"
    canceled = "canceled"


class TaskSubmitResponse(BaseModel):
    """Response model for submitting a task"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: Annotated[str, Field(examples=["task-123"], title="Task Id")]
    """
    Identifier of the submitted task

    Example: 'task-123'
    """
    task_uri: Annotated[str, Field(frozen=True, title="Task Uri")]
    """The list of past events in this incident"""


class VolumeMount(BaseModel):
    """Represents a volume mount for a container."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    source: Annotated[
        str, Field(examples=["/data/project"], min_length=1, title="Source")
    ]
    """
    The source path on the host system to mount

    Example: '/data/project'
    """
    target: Annotated[str, Field(examples=["/mnt/data"], min_length=1, title="Target")]
    """
    The target path inside the container where the volume will be mounted

    Example: '/mnt/data'
    """
    read_only: Annotated[bool, Field(examples=[True], title="Read Only")] = True
    """
    Whether the mount should be read-only

    Example: True
    """


class AllocationEntry(BaseModel):
    """Base class for allocations."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    allocation: Annotated[float, Field(examples=[100000.0], title="Allocation")]
    """
    Total allocation amount granted.

    Example: 100000.0
    """
    usage: Annotated[float, Field(examples=[52342.5], title="Usage")]
    """
    Amount of allocation consumed.

    Example: 52342.5
    """
    unit: Annotated[AllocationUnit, Field(examples=["node_hours"])]
    """
    Unit of the allocation (e.g., node_hours, bytes).

    Example: 'node_hours'
    """


class Container(BaseModel):
    """
    Represents a container specification for job execution.

    Implementation notes: The value of gpu_cores_per_process in ResourceSpec should be used to determine
    if the container should be run with GPU support. Likewise, the value of launcher in JobSpec should be used
    to determine if the container should be run with MPI support. The container should by default. be run with
    host networking.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    image: Annotated[
        str,
        Field(
            examples=["docker.io/library/ubuntu:latest"], min_length=1, title="Image"
        ),
    ]
    """
    The container image to use (e.g., 'docker.io/library/ubuntu:latest')

    Example: 'docker.io/library/ubuntu:latest'
    """
    volume_mounts: Annotated[list[VolumeMount] | None, Field(title="Volume Mounts")] = (
        None
    )
    """List of volume mounts for the container"""


class Event(BaseModel):
    """Represents an event that occurred to a resource, which may be part of an incident."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["urn:iri:object:1234"], title="Id")]
    """
    The unique identifier for the object. Typically a UUID or URN.

    Example: 'urn:iri:object:1234'
    """
    name: Annotated[str | None, Field(examples=["Perlmutter GPU"], title="Name")] = None
    """
    The long name of the object.

    Example: 'Perlmutter GPU'
    """
    description: Annotated[
        str | None,
        Field(examples=["High-performance GPU compute resource"], title="Description"),
    ] = None
    """
    Human-readable description of the object.

    Example: 'High-performance GPU compute resource'
    """
    last_modified: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Last Modified")
    ]
    """
    ISO 8601 timestamp when this object was last modified.

    Example: '2026-02-21T12:00:00Z'
    """
    occurred_at: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Occurred At")
    ]
    """
    Timestamp when the event occurred

    Example: '2026-02-21T12:00:00Z'
    """
    status: Annotated[Status, Field(examples=["down"])]
    """
    Status of the resource at the time of the event

    Example: 'down'
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """The canonical URL of this object"""
    resource_uri: Annotated[str, Field(frozen=True, title="Resource Uri")]
    """The resource belonging to this event"""
    incident_uri: Annotated[str | None, Field(frozen=True, title="Incident Uri")]
    """The event's incident"""


class Incident(BaseModel):
    """Represents an incident that may impact one or more resources."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["urn:iri:object:1234"], title="Id")]
    """
    The unique identifier for the object. Typically a UUID or URN.

    Example: 'urn:iri:object:1234'
    """
    name: Annotated[str | None, Field(examples=["Perlmutter GPU"], title="Name")] = None
    """
    The long name of the object.

    Example: 'Perlmutter GPU'
    """
    description: Annotated[
        str | None,
        Field(examples=["High-performance GPU compute resource"], title="Description"),
    ] = None
    """
    Human-readable description of the object.

    Example: 'High-performance GPU compute resource'
    """
    last_modified: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Last Modified")
    ]
    """
    ISO 8601 timestamp when this object was last modified.

    Example: '2026-02-21T12:00:00Z'
    """
    status: Annotated[Status, Field(examples=["degraded"])]
    """
    Current status of the incident

    Example: 'degraded'
    """
    start: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Start")
    ]
    """
    Incident start time

    Example: '2026-02-21T12:00:00Z'
    """
    end: Annotated[
        AwareDatetime | None, Field(examples=["2026-02-21T14:00:00Z"], title="End")
    ] = None
    """
    Incident end time

    Example: '2026-02-21T14:00:00Z'
    """
    type: Annotated[IncidentType, Field(examples=["planned"])]
    """
    Type of incident

    Example: 'planned'
    """
    resolution: Annotated[Resolution, Field(examples=["pending"])]
    """
    Resolution status of the incident

    Example: 'pending'
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """The canonical URL of this object"""
    event_uris: Annotated[list[str], Field(frozen=True, title="Event Uris")]
    """The list of past events in this incident"""
    resource_uris: Annotated[list[str], Field(frozen=True, title="Resource Uris")]
    """The list of resources that may be impacted by this incident"""


class JobSpec(BaseModel):
    """Specification for a job."""

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    executable: Annotated[
        Executable | None, Field(examples=["/usr/bin/python"], title="Executable")
    ] = None
    """
    Path to the executable to run. If container is specified, this will be used as the entrypoint to the container.

    Example: '/usr/bin/python'
    """
    container: Container | None = None
    """Container specification for containerized execution"""
    arguments: Annotated[
        list[str] | None, Field(examples=[["-n", "100"]], title="Arguments")
    ] = None
    """
    Command-line arguments to pass to the executable or container

    Example: ['-n', '100']
    """
    directory: Annotated[
        Directory | None, Field(examples=["/home/user/work"], title="Directory")
    ] = None
    """
    Working directory for the job

    Example: '/home/user/work'
    """
    name: Annotated[Name | None, Field(examples=["my-job"], title="Name")] = None
    """
    Name of the job

    Example: 'my-job'
    """
    inherit_environment: Annotated[
        bool, Field(examples=[True], title="Inherit Environment")
    ] = True
    """
    Whether to inherit the environment variables from the submission environment

    Example: True
    """
    environment: Annotated[
        dict[str, str] | None,
        Field(examples=[{"OMP_NUM_THREADS": "4"}], title="Environment"),
    ] = None
    """
    Environment variables to set for the job. If container is specified, these will be set inside the container.

    Example: {'OMP_NUM_THREADS': '4'}
    """
    stdin_path: Annotated[
        StdinPath | None, Field(examples=["/home/user/input.txt"], title="Stdin Path")
    ] = None
    """
    Path to file to use as standard input

    Example: '/home/user/input.txt'
    """
    stdout_path: Annotated[
        StdoutPath | None,
        Field(examples=["/home/user/output.txt"], title="Stdout Path"),
    ] = None
    """
    Path to file to write standard output

    Example: '/home/user/output.txt'
    """
    stderr_path: Annotated[
        StderrPath | None, Field(examples=["/home/user/error.txt"], title="Stderr Path")
    ] = None
    """
    Path to file to write standard error

    Example: '/home/user/error.txt'
    """
    resources: ResourceSpec | None = None
    """Resource requirements for the job"""
    attributes: JobAttributes | None = None
    """Additional job attributes such as duration, queue, and account"""
    pre_launch: Annotated[
        PreLaunch | None, Field(examples=["module load cuda"], title="Pre Launch")
    ] = None
    """
    Script or commands to run before launching the job

    Example: 'module load cuda'
    """
    post_launch: Annotated[
        PostLaunch | None, Field(examples=["echo done"], title="Post Launch")
    ] = None
    """
    Script or commands to run after the job completes

    Example: 'echo done'
    """
    launcher: Annotated[Launcher | None, Field(examples=["srun"], title="Launcher")] = (
        None
    )
    """
    Job launcher to use (e.g., 'mpirun', 'srun')

    Example: 'srun'
    """


class ProjectAllocation(BaseModel):
    """
    A project's allocation for a capability. (aka. repo)
    This allocation is a piece of the total allocation for the capability. (eg. 5% of the total node hours of Perlmutter GPU nodes)
    A project would at least have a storage and job repos, maybe more than 1 of each.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["alloc-001"], title="Id")]
    """
    Unique identifier of the project allocation.

    Example: 'alloc-001'
    """
    entries: Annotated[list[AllocationEntry], Field(title="Entries")]
    """Allocation entries describing usage and limits."""
    project_uri: Annotated[str, Field(frozen=True, title="Project Uri")]
    """URI of the associated project resource"""
    capability_uri: Annotated[str, Field(frozen=True, title="Capability Uri")]
    """URI of the associated capability resource"""


class Resource(BaseModel):
    """Represents a resource in the system."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["urn:iri:object:1234"], title="Id")]
    """
    The unique identifier for the object. Typically a UUID or URN.

    Example: 'urn:iri:object:1234'
    """
    name: Annotated[str | None, Field(examples=["Perlmutter GPU"], title="Name")] = None
    """
    The long name of the object.

    Example: 'Perlmutter GPU'
    """
    description: Annotated[
        str | None,
        Field(examples=["High-performance GPU compute resource"], title="Description"),
    ] = None
    """
    Human-readable description of the object.

    Example: 'High-performance GPU compute resource'
    """
    last_modified: Annotated[
        AwareDatetime, Field(examples=["2026-02-21T12:00:00Z"], title="Last Modified")
    ]
    """
    ISO 8601 timestamp when this object was last modified.

    Example: '2026-02-21T12:00:00Z'
    """
    group: Annotated[str | None, Field(examples=["frontend"], title="Group")] = None
    """
    Logical grouping of the resource

    Example: 'frontend'
    """
    current_status: Annotated[Status | None, Field(examples=["up"])] = None
    """
    The current status comes from the status of the last event for this resource

    Example: 'up'
    """
    resource_type: Annotated[ResourceType, Field(examples=["service"])]
    """
    Type of the resource

    Example: 'service'
    """
    self_uri: Annotated[str, Field(frozen=True, title="Self Uri")]
    """The canonical URL of this object"""
    site_uri: Annotated[str, Field(frozen=True, title="Site Uri")]
    """URI of the site where this resource is located"""
    capability_uris: Annotated[list[str], Field(frozen=True, title="Capability Uris")]
    """The list of capabilities in this resource"""


class Task(BaseModel):
    """Represents a task in the system."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["task-123"], title="Id")]
    """
    Unique identifier of the task

    Example: 'task-123'
    """
    status: Annotated[TaskStatus, Field(examples=["pending"])] = TaskStatus.pending
    """
    Current status of the task

    Example: 'pending'
    """
    result: Annotated[dict[str, object] | None, Field(title="Result")] = None
    """Result of the task execution, if available"""
    command: TaskCommand | None = None
    """Command associated with this task"""


class UserAllocation(BaseModel):
    """
    A user's allcation in a project.
    This allocation is a piece of the project's allocation.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["user-alloc-42"], title="Id")]
    """
    Unique identifier of the user allocation.

    Example: 'user-alloc-42'
    """
    user_id: Annotated[str, Field(examples=["user-123"], title="User Id")]
    """
    Identifier of the user receiving this allocation.

    Example: 'user-123'
    """
    entries: Annotated[list[AllocationEntry], Field(title="Entries")]
    """Allocation entries describing usage and limits."""
    project_allocation_uri: Annotated[
        str, Field(frozen=True, title="Project Allocation Uri")
    ]
    """URI of the associated project allocation"""


class Job(BaseModel):
    """Represents a job in the system."""

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: Annotated[str, Field(examples=["job-12345"], title="Id")]
    """
    Unique identifier of the job

    Example: 'job-12345'
    """
    status: JobStatus | None = None
    """Current status of the job"""
    job_spec: JobSpec | None = None
    """Specification used to create the job"""
